export { default as Home } from './home'
export { default as Login } from './login'
export { default as Register } from './register'
export { default as Leads } from './leads'
export { default as Perfil } from './perfil'
